app/routes/provider.py
from flask import session  # import session
from flask import render_template, Blueprint, send_from_directory
from app import db
from flask import abort
from app.config import Config
from app.database.models import (
    TblFundorte,
    TblMeldungen,
    TblUsers,
    TblFundortBeschreibung,
    TblMeldungUser,
)

# Blueprints
provider = Blueprint("provider", __name__)


@provider.route("/report/<usrid>")
@provider.route("/sichtungen/<usrid>")
def melder_index(usrid):
    "Index page for the provider. The users reports are displayed here."
    # First find the user making the request with role 1 or 9
    user = TblUsers.query.filter_by(user_id=usrid).first()

    # If the user doesn't exist or the role isn't 1 or 9, return 404
    if not user or (user.user_rolle != "1" and user.user_rolle != "9"):
        abort(404)

    # Store the userid in session
    session["user_id"] = usrid

    image_path = Config.UPLOAD_FOLDER.replace("app/", "")

    # Get the user's email if provided
    user_email = user.user_kontakt if user.user_kontakt else None

    # Base query with all the necessary joins
    base_query = (
        db.session.query(
            TblMeldungen.id,
            TblMeldungen.dat_fund_von,
            TblMeldungen.dat_fund_bis, 
            TblMeldungen.dat_meld,
            TblMeldungen.dat_bear,
            TblMeldungen.tiere,
            TblMeldungen.fo_quelle,
            TblMeldungen.art_m,
            TblMeldungen.art_w,
            TblMeldungen.art_n,
            TblMeldungen.art_o,
            TblMeldungen.art_f,
            TblMeldungen.anm_melder,
            TblFundortBeschreibung.beschreibung,
            TblUsers.user_id,
            TblUsers.user_name,
            TblUsers.user_kontakt,
            TblFundorte.plz,
            TblFundorte.ort,
            TblFundorte.strasse,
            TblFundorte.land,
            TblFundorte.kreis,
            TblFundorte.longitude,
            TblFundorte.latitude,
            TblFundorte.ablage,
        )
        .join(TblMeldungUser, TblMeldungen.id == TblMeldungUser.id_meldung)
        .join(TblUsers, TblMeldungUser.id_user == TblUsers.id)
        .join(TblFundorte, TblMeldungen.fo_zuordnung == TblFundorte.id)
        .join(
            TblFundortBeschreibung,
            TblFundorte.beschreibung == TblFundortBeschreibung.id,
        )
    )

    # Apply email filter only if user has an email
    if user_email:
        sichtungen_query = base_query.filter(TblUsers.user_kontakt == user_email).all()
    else:
        sichtungen_query = base_query.filter(TblUsers.user_id == usrid).all()

    # Process query results
    sichtungen = []
    for sighting in sichtungen_query:
        sighting_dict = sighting._asdict()
        sighting_dict["dat_bear"] = sighting_dict["dat_bear"] or "noch nicht geprüft"
        sichtungen.append(sighting_dict)

    return render_template(
        "provider/melder.html", reported_sightings=sichtungen, image_path=image_path
    )


@provider.route("/<path:filename>")
def report_Img(filename):
    "Return the image file for the report with the given filename."
    return send_from_directory(
        Config["UPLOAD_PATH"], filename, mimetype="image/webp", as_attachment=False
    )

app/templates/provider/melder.html
{% extends "layout.html" %}
{% block title %} Meine Sichtungen {% endblock title %}
{% block button_ref %} "/melden/{{ session['user_id'] }}" {% endblock %}
{% block content %}

<div class="container px-4 mx-auto my-10 md:px-12">
  <div class="my-4 text-center">
    <h1 class="my-1 text-4xl font-semibold text-gray-900">
      Ihre bisherigen Meldungen
    </h1>
    <hr class="w-1/4 mx-auto my-4 border-t-2 border-green-600" />
  </div>
  {% if reported_sightings %}
  <div class="grid grid-cols-1 gap-6 mb-4 sm:grid-cols-2 lg:grid-cols-3" id="reportContainer">
    {% for sighting in reported_sightings %}
    <div
      class="mb-8 overflow-hidden transition-shadow duration-300 ease-in-out bg-white rounded-lg shadow-lg hover:shadow-2xl report-card">
      <div class="relative">
        <img loading="lazy" onclick="openImageModal('{{ url_for('provider.report_Img', filename=image_path + "/" + sighting.ablage)}}')"
          class="object-cover w-full h-48 transition-transform duration-200 ease-in-out rounded-t-lg cursor-pointer md:h-64 hover:scale-105"
          src="{{ url_for('provider.report_Img', filename=image_path + "/" + sighting.ablage)}}"
          alt="{{sighting.imagepath}}">
        <div
          title="{{sighting.ort}}&#13;&#10;Postleitzahl: {{sighting.plz}}&#13;&#10;Kreis: {{sighting.kreis}}&#13;&#10;Land: {{sighting.land}}"
          class="absolute bottom-0 px-3 py-1 mb-4 ml-4 font-semibold text-gray-800 rounded-full bg-white/80 backdrop-blur-md">
          {{sighting.kreis}} | {{sighting.ort}}</div>
        <span
          class="absolute inline-block px-2 py-1 font-semibold leading-none tracking-wide text-gray-100 uppercase bg-green-500 rounded-full top-2 left-2">
          {{sighting.id}}</span>
      </div>
      <div class="p-4 bg-white rounded-lg shadow-lg">
        <h4 class="mt-2 text-lg font-semibold leading-tight truncate md:text-xl">
          <p class="text-sm">
            <strong>Melde-ID:</strong> {{sighting.id}}
          </p>
        </h4>
        <div class="mt-2">
          <p class="text-sm">
            <strong>Melde-Datum:</strong> {{sighting.dat_meld}}
          </p>
          <p class="text-sm">
            <strong>Fund-Datum:</strong> {{sighting.dat_fund_von}}
          </p>
          <p class="text-sm">
            <strong>Kreis:</strong> {{sighting.kreis}}
          </p>
          <p class="text-sm">
            <strong>Längengrad:</strong> {{sighting.longitude}}
          </p>
          <p class="text-sm">
            <strong>Breitengrad:</strong> {{sighting.latitude}}
          </p>
          <p class="text-sm">
            <strong>Datum der Überprüfung:</strong> {{sighting.dat_bear}}
          </p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% else %}
  <div class="text-center">
    <h2 class="text-xl font-semibold text-gray-900">Keine Meldungen gefunden</h2>
    <p class="mt-2 text-gray-600">Es wurden keine Meldungen von Ihnen gefunden. Beginnen Sie mit Ihrer ersten Meldung, indem Sie den Button oben nutzen.</p>
  </div>
  {% endif %}

<div id="imageModal" class="fixed inset-0 z-50 hidden overflow-y-auto" aria-labelledby="imageModalLabel" tabindex="-1"
  title="Um das Bild weiter zu vergrößern klicken sie auf den Button unten">
  <div class="flex items-center justify-center min-h-screen px-4 pt-4 pb-20 text-center sm:block sm:p-0">
    <div id="imageModalBackdrop" class="fixed inset-0 transition-opacity" aria-hidden="true">
      <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
    </div>
    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
    <div
      class="inline-block px-4 pt-5 pb-4 overflow-hidden text-left align-bottom transition-all transform bg-white rounded-lg shadow-xl sm:my-8 sm:align-middle sm:max-w-full sm:w-11/12 md:w-3/4 lg:w-1/2 xl:w-1/3 sm:p-6">
      <div class="flex justify-center mt-2">
        <img loading="lazy" id="modalImage" class="w-full max-h-[70vh] object-cover" src="" alt="Full Image View" />
      </div>
      <div class="mt-5 sm:mt-4 sm:flex sm:flex-row-reverse">
        <button type="button" onclick="closeImageModal()"
          class="inline-flex justify-center w-full px-4 py-2 mb-2 text-base font-medium text-gray-100 bg-green-600 border border-transparent rounded-md shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 sm:mb-0 sm:ml-3 sm:w-auto sm:text-sm"
          title="Schließen Sie das Fenster">
          Close
        </button>
        <button type="button" onclick="openImageNewTab()"
          class="inline-flex justify-center w-full px-4 py-2 mb-2 text-base font-medium text-gray-100 bg-green-600 border border-transparent rounded-md shadow-sm hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500 sm:mb-0 sm:ml-3 sm:w-auto sm:text-sm"
          title="Öffnen Sie das Bild in einem neuen Tab">
          <svg class="w-[16px] h-[16px] text-gray-100" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
            viewBox="0 0 18 18">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11v4.833A1.166 1.166 0 0 1 13.833 17H2.167A1.167 1.167 0 0 1 1 15.833V4.167A1.166
			 1.166 0 0 1 2.167 3h4.618m4.447-2H17v5.768M9.111 8.889l7.778-7.778" />
          </svg>
        </button>
      </div>
    </div>
  </div>
</div>


</div>
<div class="p-5 mt-5 text-center bg-white shadow rounded-2xl">
  <p class="text-lg font-medium text-gray-700">
    Vielen Dank für Ihre Unterstützung.
  </p>
  <p class="text-lg font-bold text-green-600">-== Ihr Mantis-Team ==-</p>
  <p class="mt-2 text-sm font-medium text-gray-500">
    HINWEIS: Behandeln Sie diesen Link wie ein Passwort und geben Sie ihn
    nicht weiter!
  </p>
</div>
</div>
<script>
  function openImageModal(imageUrl) {
    document.body.style.overflow = "hidden";
    document.getElementById("modalImage").src = imageUrl;
    document.getElementById("imageModal").style.display = "block";
 }
  function closeImageModal() {
    document.getElementById("imageModal").style.display = "none";
    document.body.style.overflow = "auto";
 }
  function openImageNewTab() {
    let modalImage = document.getElementById("modalImage");
    window.open(modalImage.src, "_blank");
 }

  document.addEventListener("DOMContentLoaded", function () {
    document
      .getElementById("imageModalBackdrop")
      .addEventListener("click", closeImageModal);
 });
</script>
{% endblock content %}