app/routes/data.py
import json
import os
from datetime import datetime, timedelta
from pathlib import Path
from random import uniform
from PIL import Image
import io

from flask import (
    Blueprint,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    url_for,
    abort,
    session,
)
from werkzeug.datastructures import CombinedMultiDict
from werkzeug.utils import secure_filename

from app import db
from app.database.models import TblFundorte, TblMeldungen, TblMeldungUser, TblUsers
from app.forms import MantisSightingForm
from app.tools.gen_user_id import get_new_id
from app.tools.mtb_calc import get_mtb, pointInRect
from app.tools.find_gemeinde import get_amt_full_scan

from ..config import Config

# Blueprints
data = Blueprint("data", __name__)
checklist = Config.CHECKLIST
checklist["datum"] = datetime.now() + timedelta(days=1)

# Load the popover content from flask static folder
popover_content = {}
popover_content_path = os.path.join(Config.STATIC_FOLDER, "popover_content.json")
if os.path.exists(popover_content_path):
    with open(popover_content_path, "r") as f:
        popover_content = json.load(f)

        
def _create_directory(date):
    year = date[:4]
    dir_path = Path(Config.UPLOAD_FOLDER + "/" + year + "/" + date)
    dir_path.mkdir(parents=True, exist_ok=True)
    return dir_path


def _create_filename(location, usrid):
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    return "{}-{}-{}.webp".format(
        secure_filename(location), timestamp, secure_filename(usrid)
    )


def _allowed_file(filename):
    return (
        "." in filename
        and filename.rsplit(".", 1)[1].lower() in Config.ALLOWED_EXTENSIONS
    )


def _update_or_create_user(
    usrid, last_name, first_name, contact, finder_last_name, finder_first_name
):
    existing_user = TblUsers.query.filter_by(user_id=usrid).first()

    new_finder = None
    if finder_first_name and finder_last_name:
        finderid = get_new_id()
        new_finder = TblUsers(
            user_id=finderid,
            user_name=f"{finder_last_name.strip()} {finder_first_name.strip()[0].upper()}.",
            user_rolle=2,
        )
        db.session.add(new_finder)
        db.session.flush()

    if not existing_user:
        new_user = TblUsers(
            user_id=usrid,
            user_name=f"{last_name.strip()} {first_name.strip()[0].upper()}.",
            user_rolle=1,
            user_kontakt=contact,
        )
        db.session.add(new_user)
        db.session.flush()
        return new_user, new_finder
    return existing_user, new_finder


def _handle_file_upload(request, form, usrid):
    if "picture" not in request.files:
        flash("No file part")
        return None
    file = request.files["picture"]

    if file.filename == "" or not _allowed_file(file.filename):
        flash("No selected file")
        return None

    date_folder = _create_directory(form.sighting_date.data.strftime("%Y-%m-%d"))
    filename = _create_filename(form.fund_city.data, usrid)
    full_file_path = date_folder / filename

    # Read the file content
    file_content = file.read()

    # Use Pillow to open the image
    with Image.open(io.BytesIO(file_content)) as img:
        # Check if the image is already in WebP format or over 6MB  
        if img.format != 'WEBP' or len(file_content) > 6 * 1024 * 1024:
            # Convert to WebP
            output = io.BytesIO()
            img.save(output, format='WEBP', quality=50)
            output.seek(0)
            file_content = output.getvalue()

    # Save the WebP image
    with open(str(full_file_path), 'wb') as f:
        f.write(file_content)

    return str(full_file_path.as_posix())


def _set_gender_fields(selected_gender):
    genders = {"art_m": 0, "art_w": 0, "art_n": 0, "art_o": 0}
    gender_mapping = {
        "Männchen": "art_m",
        "Weibchen": "art_w",
        "Nymphe": "art_n",
        "Oothek": "art_o",
    }
    gender_field = gender_mapping.get(selected_gender)

    if gender_field:
        genders[gender_field] = 1

    return genders


def _user_to_dict(user):
    return {
        "user_name": user.user_name,
        "user_kontakt": user.user_kontakt,
    }


def _saveip(ip):
    "Manage IPs to allow only one report/day"
    global checklist
    today = datetime.now()
    nextday = checklist.get("datum", None)
    # reset checklist if one day has left
    if today > nextday:
        checklist.clear()
        checklist["datum"] = datetime.now() + timedelta(days=1)
    if ip not in checklist:
        checklist[ip] = 0
    else:
        checklist[ip] += 1
    return


@data.route("/melden", methods=["GET", "POST"])
@data.route("/melden/<usrid>", methods=["GET", "POST"])
def report(usrid=None):

    existing_user = TblUsers.query.filter_by(user_id=usrid).first() if usrid else None
    if not existing_user:
        usrid = get_new_id()

    form = MantisSightingForm(userid=usrid, meta={"locales": ["de_DE", "de"]})

    if existing_user and request.method == "GET":
        form.process(obj=existing_user)
        form.report_first_name.render_kw = {"readonly": "readonly"}
        form.report_last_name.render_kw = {"readonly": "readonly"}
        form.contact.render_kw = {"readonly": "readonly"}

    if request.method == "POST":
        # Rate-limiting logic only for POST requests
        global checklist
        ip = request.remote_addr
        pid = os.getpid()
        mark = f"{ip}:{pid}"
        _saveip(mark)
        if checklist.get(mark) > 7:
            abort(429)

    if form.validate_on_submit():

        honeypot_value = form.honeypot.data
        # If the honeypot field is filled out, redirect or return an error
        if honeypot_value:
            # Redirect to an error page or handle as needed
            abort(403)

        bildpfad = _handle_file_upload(request, form, usrid).replace(
            Config.UPLOAD_FOLDER + "/", ""
        )

        if not form.fund_zip_code.data:
            zipcode = "0"
        else:
            zipcode = form.fund_zip_code.data
        # get number of Messtischblatt
        if pointInRect((form.latitude.data, form.longitude.data)):
            mtb = get_mtb(form.latitude.data, form.longitude.data)
            amt = get_amt_full_scan((form.longitude.data, form.latitude.data))
        else:
            mtb = ""
            amt = ""

        new_fundort = TblFundorte(
            plz=zipcode,
            ort=form.fund_city.data,
            strasse=form.fund_street.data,
            kreis=form.fund_district.data,
            land=form.fund_state.data,
            longitude=form.longitude.data,
            latitude=form.latitude.data,
            mtb=mtb,
            amt=amt,
            beschreibung=int(form.location_description.data),
            ablage=bildpfad,
        )
        db.session.add(new_fundort)
        db.session.flush()

        genders = _set_gender_fields(form.gender.data)

        new_meldung = TblMeldungen(
            dat_fund_von=form.sighting_date.data,
            dat_meld=datetime.now(),
            fo_zuordnung=new_fundort.id,
            fo_quelle="F",
            art_f="0",
            tiere="1",
            **genders,
            anm_melder=form.picture_description.data,
        )
        db.session.add(new_meldung)
        db.session.flush()

        updated_user, updated_finder = _update_or_create_user(
            usrid,
            form.report_last_name.data,
            form.report_first_name.data,
            form.contact.data,
            form.finder_first_name.data,
            form.finder_last_name.data,
        )

        if updated_finder:
            new_meldung_user = TblMeldungUser(
                id_meldung=new_meldung.id,
                id_user=updated_user.id,
                id_finder=updated_finder.id,
            )
        else:
            new_meldung_user = TblMeldungUser(
                id_meldung=new_meldung.id, id_user=updated_user.id
            )

        db.session.add(new_meldung_user)
        db.session.commit()
        addresse = form.contact.data
        # set submission_successfull to True
        session["submission_successful"] = True
        return redirect(
            url_for("data.success", usrid=usrid, addresse=str(bool(addresse)))
        )

    if existing_user is not None:
        existing_user = _user_to_dict(existing_user)
    return render_template(
        "report.html",
        form=form,
        existing_user=existing_user,
        apikey=Config.esri,
        popover_content=popover_content
    )


@data.route("/success/<usrid>")
def success(usrid):
    "Prevent reloading of success route after first submission."

    if not session.get("submission_successful"):
        return redirect(url_for("main.index"))

    session["submission_successful"] = False

    addresse = request.args.get("addresse", None)
    return render_template("success.html", usrid=usrid, addresse=addresse)


@data.route("/validate", methods=["POST"])
def validate():
    "Validate user input in report with the errors from forms.py"

    form_data = CombinedMultiDict((request.form, request.files))  # type: ignore
    form = MantisSightingForm(form_data)

    if form.validate():
        return jsonify({"success": True})
    else:
        return jsonify({"errors": form.errors}), 333


@data.route("/auswertungen")
def show_map():
    selected_year = request.args.get("year", None, type=int)
    "Select data for one selected year"

    # Get distinct years from dat_fund_von begginning with MIN_MAP_YEAR
    years = (
        db.session.query(
            db.func.extract("year", TblMeldungen.dat_fund_von).label("year")
        )
        .distinct()
        .order_by("year")
        .filter(TblMeldungen.dat_fund_von >= f"{Config.MIN_MAP_YEAR}-01-01")
    )
    years = [int(year[0]) for year in years]

    reports_query = (
        db.session.query(TblMeldungen.id, TblFundorte.latitude, TblFundorte.longitude)

app/templates/galerie.html
{% from "macro.html" import popoverOld %}

{% extends "layout.html" %}
{% block title %}Bildergalerie{% endblock title %}
{% block meta_keywords %}Auswertungen, Bilder, Gottesanbeterin, Mantis religiosa Auswertungen{% endblock %}
{% block content %}
<script src="{{ url_for('static', filename='js/flow/flowbite.min.js')}}" defer></script>
<section class="container mx-auto mt-10">
  <div class="flex items-center justify-center mb-6">
    <h2 class="text-4xl font-extrabold text-center text-gray-900 sm:flex sm:flex-col sm:items-center">
      <span class="sm:hidden">Interessante<br> Momentaufnahmen</span>
      <span class="hidden sm:block">Interessante Momentaufnahmen</span>
    </h2>
    {{ popoverOld('hinweise-popover', 'Hinweise zur Bedienung', '<ul><li>Das Bild anklicken, Bilderserie startet …</li><li>Mit Pfeil nach rechts, vorblättern …</li><li>Mit Pfeil nach links, zurückblättern …</li><li>Mit ESC-Taste, die Bilderschau beenden …</li></ul>') }}
  </div>
  <div class="grid grid-cols-1 gap-4 px-2 md:grid-cols-3 lg:grid-cols-4 xl:px-8 auto-rows-[1fr]">
    <link href="{{ url_for('static', filename='lb/css/lightbox.min.css')}}" rel="stylesheet">
    
    {% for slide in bilder %}
    <div class="aspect-w-16 aspect-h-9">
      <a href="{{ url_for('static', filename='images/galerie/' + slide.bildname)}}"
         rel="lightbox[Mantis]"
         title="{{ slide.beschreibung }} <br />Autor: {{ slide.fotograph }} <br />Funddatum: {{ slide.funddatum }} <br />Lizenz: {{ slide.lizenz | safe }}"
         class="transition-opacity duration-300 hover:opacity-75">
        <img src="{{ url_for('static', filename='images/galerie/' + slide.bildname)}}"
             alt="Gallery Image"
             class="object-cover w-full h-full rounded-lg shadow-lg">
      </a>
    </div>
    {% endfor %}
    
  </div>
</section>

<script src="{{ url_for('static', filename='lb/jquery-3.3.1.slim.min.js')}}"></script>
<script src="{{ url_for('static', filename='lb/js/lightbox-plus-jquery.js')}}"></script>

{% endblock content %}

app/templates/mantis_religiosa.html
{% extends "layout.html" %}

{% block meta_keywords %}
Mantis religiosa, Informationen, Gottesanbeterin Fakten, Lebensraum, Erkennungsmerkmale, Verbreitung, Lebenszyklus,
Beobachtungstipps, Brandenburg, Berlin, Fangschrecken, Insekten, Biodiversität, Artenschutz, Ökologie
{% endblock %}

{% block meta_description %}
Umfassende Informationen über Mantis religiosa (Europäische Gottesanbeterin): Steckbrief, Habitat, Verbreitung,
Lebenszyklus und Beobachtungstipps. Erfahren Sie mehr über dieses faszinierende Insekt und seine Rolle in unserem
Ökosystem.
{% endblock %}

{% block page_title %}
Mantis Religiosa: Umfassende Informationen zur Europäischen Gottesanbeterin | Gottesanbeterin Gesucht
{% endblock %}

{% block head %}
{{ super() }}
<meta property="og:type" content="article" />
<meta property="article:published_time" content="2023-10-09" />
<meta property="article:modified_time" content="2023-10-09" />
<meta property="article:author" content="Gottesanbeterin Gesucht Team" />
<meta property="article:section" content="Insektenkunde" />
<meta property="article:tag" content="Mantis religiosa,Gottesanbeterin,Fangschrecken,Insekten,Biodiversität" />
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Article",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://gottesanbeterin-gesucht.de/mantis-religiosa"
  },
  "headline": "Mantis Religiosa: Umfassende Informationen zur Europäischen Gottesanbeterin",
  "description": "Umfassende Informationen über Mantis religiosa (Europäische Gottesanbeterin): Steckbrief, Habitat, Verbreitung, Lebenszyklus und Beobachtungstipps.",
  "image": "{{ url_for('static', filename='images/mantis--maennchen__krueger.webp', _external=True) }}",
  "author": {
    "@type": "Organization",
    "name": "Gottesanbeterin Gesucht Team"
  },
  "publisher": {
    "@type": "Organization",
    "name": "Gottesanbeterin Gesucht",
    "logo": {
      "@type": "ImageObject",
      "url": "{{ url_for('static', filename='favicon.ico', _external=True) }}"
    }
  },
  "datePublished": "2023-10-09",
  "dateModified": "2023-10-09"
}
</script>
<style>
  .section-anchor {
    display: block;
    position: relative;
    top: -80px;
    visibility: hidden;
  }
</style>
{% endblock %}

{% block title %}
<i>Mantis religiosa</i><br />
<span class="text-base">(ein geschütztes Tier)</span>
{% endblock title %}

{% block content %}
<main class="container px-4 py-12 mx-auto sm:px-6 lg:px-8">
  <div class="grid grid-cols-1 gap-8 md:grid-cols-4">
    <aside class="order-2 md:col-span-1 md:order-1">
      <div class="sticky top-20">
        <nav class="p-4 bg-white rounded-lg shadow-lg">
          <h2 class="mb-2 text-xl font-bold">Inhaltsverzeichnis</h2>
          <ul class="mb-2">
            <li class="mb-2"><a href="#steckbrief">Steckbrief</a></li>
            <li class="mb-2"><a href="#ueberblick">Überblick</a></li>
            <li class="mb-2"><a href="#habitat">Habitat</a></li>
            <li class="mb-2"><a href="#verbreitungsgebiet">Verbreitungsgebiet</a></li>
            <li class="mb-2"><a href="#lebenszyklus">Lebenszyklus</a></li>
            <li class="mb-2"><a href="#beobachtungstipps">Beobachtungstipps</a></li>
            <li class="mb-2"><a href="#bestimmung">Bestimmungsschlüssel</a></li>
            <li class="mb-2"><a href="#weiterfuehrende-links">Weiterführende Links</a></li>
            <li class="mb-2"><a href="#meldeformular">Meldeformular</a></li>
          </ul>
        </nav>
      </div>
    </aside>
    <article class="order-1 md:col-span-3 md:order-2">
      <div class="p-8 bg-white rounded-lg shadow-lg">
        <h1 class="mb-4 text-3xl font-bold">
          Die faszinierende Welt der
          <a href="https://de.wikipedia.org/wiki/Mantis" target="_blank">Gottesanbeterin</a>
        </h1>
        <img loading="lazy" class="mb-4 rounded"
          src="{{ url_for('static', filename='images/mantis--maennchen__krueger.webp') }}"
          alt="Profil einer männlichen Mantis religiosa">
        <p class="text-sm text-gray-600">Bildquelle: Krüger B. 2012</p>
        <div class="text-lg leading-normal text-gray-800">
          <span id="steckbrief" class="section-anchor"></span>
          <section class="mb-8">
            <h2 class="mb-2 text-2xl font-bold text-gray-800">Steckbrief</h2>
            <dl>
              <dt class="font-bold">Wissenschaftlicher Name:</dt>
              <dd><i>Mantis religiosa</i> L., 1758</dd>
              <dt class="font-bold">Ordnung:</dt>
              <dd><em><a href="https://de.wikipedia.org/wiki/Mantodea" target="_blank">Fangschrecken (Mantodea)</a></em>
              </dd>
              <dt class="font-bold">Größe:</dt>
              <dd><em>Weibchen 7 cm, Männchen 5-6 cm</em></dd>
              <dt class="font-bold">Lebensraum:</dt>
              <dd><em>Offene Grasfluren, Brachen, Ruderalflächen, Gärten</em></dd>
              <dt class="font-bold">Verbreitung:</dt>
              <dd><em>Europa, Asien, Afrika</em></dd>
              <dt class="font-bold">Lebensweise:</dt>
              <dd><em>Räuberisch</em></dd>
              <dt class="font-bold">Ernährung:</dt>
              <dd><em>Vorwiegend Insekten und Spinnentiere</em></dd>
            </dl>
          </section>
          <span id="ueberblick" class="section-anchor"></span>
          <section class="mb-8">
            <h2 class="mb-2 text-2xl font-bold text-gray-800">Überblick</h2>
            <p>
              Die Europäische Gottesanbeterin (<i>Mantis religiosa</i>) ist eine Fangschreckenart, deren
              Verbreitungsgebiet sich vom südlichen Europa bis nach Asien erstreckt. Ursprünglich nur in
              Rheinland-Pfalz, Baden-Württemberg und dem Saarland gefunden, breitet sie sich seit den 1990er Jahren
              Richtung Norden aus. In Brandenburg wurde sie erstmals 2007 gesichtet und ist nun in der Südhälfte recht
              weit verbreitet.
            </p>
            <img loading="lazy" class="mb-4 rounded"
              src="{{ url_for('static', filename='images/mantis--weibchen__krueger.webp') }}"
              alt="Weibliche Mantis religiosa bei der Jagd">
            <p class="text-sm text-gray-600">Bildquelle: Krüger B. 2005</p>
          </section>
          <span id="habitat" class="section-anchor"></span>
          <section class="mb-8">
            <h2 class="mb-2 text-2xl font-bold text-gray-800">Habitat</h2>
            <p>
              Die Gottesanbeterin ist eine wärmeliebende Art und bevorzugt sonnige Lebensräume wie offene Grasfluren mit
              strukturgebenden Stauden, Brachen und Ruderalflächen. Überraschend oft findet man sie auch in Gärten und
              innerhalb von Ortschaften und Städten. In geschlossenen Wäldern wird man sie hingegen nicht finden.
            </p>
          </section>
          <span id="verbreitungsgebiet" class="section-anchor"></span>
          <section class="mb-8">
            <h2 class="mb-2 text-2xl font-bold text-gray-800">Verbreitungsgebiet</h2>
            <p>
              Das Verbreitungsgebiet der Europäischen Gottesanbeterin erstreckt sich vom südlichen Europa von Portugal
              über Spanien, Frankreich, Italien, über den Balkan, in die Türkei bis nach Asien. Auch in Afrika kommt die
              Gottesanbeterin vor. Aktuell ist die Fangschrecke in der Südhälfte Brandenburgs recht weit verbreitet, in
              den nördlichen Landkreisen hingegen liegen erst seit Kurzem vereinzelte Meldungen vor. Auch in Berlin wird
              die Art immer häufiger nachgewiesen.
            </p>
          </section>
          <span id="lebenszyklus" class="section-anchor"></span>
          <section class="mb-8">
            <h2 class="mb-2 text-2xl font-bold text-gray-800">Lebenszyklus</h2>
            <p>
              Die Gottesanbeterin durchläuft in ihrem Leben mehrere Stadien. Nach der Paarung legt das Weibchen ihre
              Eier in einem speziellen Schaumnest, der Oothek, ab. In unseren Breiten überwintert die Oothek; die
              erwachsenen Gottesanbeterinnen sterben im Winter. Aus diesen Eiern schlüpfen im Mai/Juni die Nymphen, die
              bereits wie kleine Gottesanbeterinnen aussehen. Sie durchlaufen mehrere Häutungen, bis sie schließlich zu
              erwachsenen Tieren heranwachsen.
            </p>
          </section>
          <span id="beobachtungstipps" class="section-anchor"></span>
          <section class="mb-8">
            <h2 class="mb-2 text-2xl font-bold text-gray-800">Beobachtungstipps</h2>
            <p>
              Die Gottesanbeterin ist tagsüber aktiv und kann bei ruhigem und vorsichtigem Herangehen gut beobachtet
              werden. Besonders gut lassen sie sich in den Morgenstunden finden, wenn sie sich an sonnigen Plätzen
              aufwärmen. Mit ihrer grünen bis braunen Färbung sind sie jedoch perfekt getarnt und nicht leicht zu
              entdecken.
            </p>
          </section>
          <span id="bestimmung" class="section-anchor"></span>
          <section class="mb-8">
            <h2 class="mb-2 text-2xl font-bold text-gray-800">Bestimmungsschlüssel</h2>
            <p>
              Wenn Sie im Meldeformular die korrekte Zuordnung eintragen möchten, können Sie mit Hilfe des
              Bestimmungsschlüssels ermitteln, ob es sich um eine Oothek, Nymphe, ein adultes Weibchen oder Männchen
              handelt.
            </p>
            <a href="/bestimmung" target="_blank"
              class="text-green-500 underline hover:text-green-400">Bestimmungsschlüssel</a>
          </section>
          <span id="weiterfuehrende-links" class="section-anchor"></span>
          <section class="mb-8">
            <h2 class="mb-2 text-2xl font-bold text-gray-800">Weiterführende Links</h2>
            <ul class="list-disc list-inside">
              <li>
                <a href="https://www.bkmakro.de/Makro/Mantiden/MR.htm" target="_blank"
                  class="text-green-500 underline hover:text-green-400">Mantidenfreunde</a>
              </li>
              <li>
                <a href="https://www.naturkundemuseum-potsdam.de/gottesanbeterin-gesucht" target="_blank"
                  class="text-green-500 underline hover:text-green-400">Naturkundemuseum Potsdam</a>
              </li>
              <li>
                <a href="https://de.wikipedia.org/wiki/Europ%C3%A4ische_Gottesanbeterin" target="_blank"
                  class="text-green-500 underline hover:text-green-400">Wikipedia Gottesanbeterin</a>
              </li>
            </ul>
          </section>
          <span id="meldeformular" class="section-anchor"></span>
          <section class="p-4 mt-8 bg-green-200 rounded-lg shadow-lg">
            <div class="flex flex-col items-center justify-between md:flex-row">
              <div class="mb-4 md:mb-0">
                <h2 class="mb-2 text-2xl font-bold text-gray-800">Meldeformular</h2>
                <p class="text-gray-700">
                  Haben Sie eine Gottesanbeterin gesichtet? Helfen Sie uns, die Verbreitung dieser faszinierenden Art
                  besser zu dokumentieren, indem Sie Ihre Beobachtung melden. Nutzen Sie dazu unser einfaches
                  Meldeformular.
                </p>
              </div>
              <a class="inline-block px-6 py-3 mt-4 text-lg font-semibold text-white transition-colors duration-200 bg-green-600 border border-transparent rounded-full shadow-lg hover:bg-green-500 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2"
                href="{{ url_for('data.report') }}">Meldeformular</a>
            </div>
          </section>
        </div>
      </div>
    </article>
  </div>
</main>

<style>
  @media (max-width: 767px) {
    .order-2 {
      order: -1;
    }
  }
</style>
{% endblock content %}